language: python
python:
  - "3.7-dev"
install:
  - pip install codecov
  - pip install -r totembionet/src/requierements.txt
script:
  - coverage run -m unittest discover -s totembionet/src
after_success:
  - codecov
