{% set name = "smb-lib" %}
{% set version = "0.1.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 46ee4874a69936696ad025a42e4d1857f7fb7939a574f3c2746324014deedf15

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python
    - requests
  run:
    - python
    - requests

test:
  imports:
    - smb_lib

about:
  home: https://github.com/clement-alexandre/TotemBionet
  license: WTFPL
  license_family: OTHER
  license_file: 
  summary: smbionet librairie python
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
