{% set name = "smb-lib" %}
{% set version = "0.0.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3f6674d0136c47881316291a612ae30d08f033d900c975af616cd380209fd86d

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - py4j
    - python
  run:
    - py4j
    - python

test:
  imports:
    - smb_lib

about:
  home: https://github.com/clement-alexandre/TotemBionet
  license: WTFPL
  license_family: OTHER
  license_file: 
  summary: smbionet librairie python
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - mohamedchennouf

target_platform:
  - linux-64
