{% set name = "smb-lib" %}
{% set version = "0.0.14" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fa29b6ff7d82a73a3dd8e0aee28735dc73a2f4298488e315d7024f8ce3fc6ce8

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - py4j
    - python
  run:
    - py4j
    - python

test:
  imports:
    - smb_lib

about:
  home: https://github.com/clement-alexandre/TotemBionet
  license: WTFPL
  license_family: OTHER
  license_file: 
  summary: smbionet librairie python
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
