{% set name = "ggea" %}
{% set version = "0.0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 662cebc241b75a27445e61bb502f50689ae00ab35c9247badc21a777ac8c0be0

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - matplotlib >=3.0.0
    - networkx >=2.0
    - pip
    - python
  run:
    - matplotlib >=3.0.0
    - networkx >=2.0
    - python

test:
  imports:
    - ggea

about:
  home: https://github.com/clement-alexandre/TotemBionet
  license: WTFPL
  license_family: OTHER
  license_file: 
  summary: Asynchronous State Graph Generator
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
