{% set name = "model-picker" %}
{% set version = "0.0.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b102d0fe2828b1be9ef83e14a6ade72a0de6e09cf9894dd322a6fdee7e5144dd

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - model_picker

about:
  home: https://github.com/clement-alexandre/TotemBionet
  license: WTFPL
  license_family: OTHER
  license_file: 
  summary: Pick a model
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
