{% set name = "ggea" %}
{% set version = "0.0.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 66dbc1adfc5d4efe1bed41af732cd84939178dfad48e9ec2d562363d0c8c3691

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - discrete-model
    - matplotlib >=3.0.0
    - networkx >=2.0
    - pip
    - pydot
    - python
  run:
    - discrete-model
    - matplotlib >=3.0.0
    - networkx >=2.0
    - pydot
    - python

test:
  imports:
    - ggea

about:
  home: https://github.com/clement-alexandre/TotemBionet
  license: WTFPL
  license_family: OTHER
  license_file: 
  summary: Asynchronous State Graph Generator
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - clement-alexandre
