{% set name = "simu-net" %}
{% set version = "0.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4bcc2f0e66bd8b50d21f9501e6019375c897954c23279a9648b0812c79a848bb

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - discrete-model
    - matplotlib >=3.0.0
    - pip
    - python
  run:
    - discrete-model
    - matplotlib >=3.0.0
    - python

test:
  imports:
    - simu_net

about:
  home: https://github.com/clement-alexandre/TotemBionet
  license: WTFPL
  license_family: OTHER
  license_file: 
  summary: Simulation library for TotemBionet
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - clement-alexandre
